### PR TITLE
Use Facebook/Instagram Graph API

### PR DESCRIPTION
**Pull request by Jeroen-G**
More or less all I had to do to make it work is to mirror the Facebook provider of Socialite but include a different scope. the benefit of having it in its own class is to differentiate between the two providers (because users also see FB and IG as different account providers).

### CODE REVIEW

**Comment by m1guelpf** [comment]
Is this backwards-compatible?

**Comment by Jeroen-G** [comment]
It requires a Facebook ID and secret. Users have to (re-)authenticate through Facebook I think. So the safest thing to do is to say it is not BC. I put it in a new application, so I cannot say with great certainty what the implications are for older applications.

**Comment by m1guelpf** [comment]
Can this be opt-in then?

**Comment by Jeroen-G** [comment]
Anything is possible. Also, that's what semver is for, isn't it?

*Except using the IG API after it's deprecation (which started January 2018).

**Comment by karljakober** [comment]
Whats the status on this? Looks like it was merged, yet the code doesnt exist anymore? Might be best to update this as instagram API now only allows basic auth and will be removed entirely in favor of facebook api in early 2020

**Comment by Jeroen-G** [comment]
I have no clue where the code went 🤔

**Comment by karljakober** [comment]
@Jeroen-G it seems upon further set up with this, that the facebook api for instagram is 'only available for Instagram business accounts.', as quoted from the set up page. so it might be best to hold off on changing anything sadly. This api migration seems to not overlap too well, and im asking the Facebook team how to progress.

**Pull request merged**
